### ISSUE TITLE
Bug: Delete all Playlists => Delete of ....more / Error Message when Delete / no Update after Delete

### ISSUE THREAD

**Issue by MartinSchneidder** [coding-bootcamps-eu/final-project-tz-2023-08-track-stack#124]
Playlist verwalten View:

1. Error Message when Delete
2. Api is updated after Delete but not in my files, maybe something wrong with the callback
3. Delete all Playlists OR Events => Delete all Requests

**Comment by MartinSchneidder** [comment]
Api: Jetzt wird bei einem Delete zwar gelöscht, aber es wird ne dicke Fehlermeldung gesendet, auch im Postman.

**Comment by IrisEnyo** [comment]
ich glaube dieses issue kann geschlossen werden?

**Comment by DonLars** [comment]
ja :)
