### ISSUE TITLE
Collect db values for ferdi

### ISSUE THREAD

**Issue by DonLars** [coding-bootcamps-eu/final-project-tz-2023-08-track-stack#136]

**Comment by IrisEnyo** [comment]
weiß zwar nicht ob das jetzt gemeint war, aber ich schick es mal hier rein. 😅 
Events:
[
{
"title": "kindergeburtstag",
"description": "12er geburtstag mit ca 20 leuten, motto monster high",
"djId": "97bd6f95-aa58-4c49-b9a8-abf4d01b51da",
"playlistId": "4fe51a4d-e55a-4399-9ed8-99f12f60ee06",
"address": "mutterstraße 14",
"startDate": "2024-06-26T18:00",
"organizer": "mutti",
"eventImage": "[/images/header_birthday.jpg](http://localhost:3000/images/header_birthday.jpg)",
"createdAt": 1715942607350,
"active": false,
"id": "63ee17ee-ccbc-4018-8b3b-524fd3951ec7"
},
{
"title": "hochzeit",
"description": "20 jähriges jubiläum",
"djId": "97bd6f95-aa58-4c49-b9a8-abf4d01b51da",
"playlistId": "9ae43aa5-7586-46e9-865d-7189aedc975a",
"address": "weddingstr. 20",
"startDate": "26.06.2024",
"organizer": "brautpaar",
"eventImage": "[/images/header_marriage.jpg](http://localhost:3000/images/header_marriage.jpg)",
"createdAt": 1716032508389,
"active": false,
"id": "39bb482c-82ab-4650-8439-991534c4bf44"
},
{
"title": "Bootcamp Abschluss",
"description": "Abschlusspräsentation des Projekts",
"djId": "97bd6f95-aa58-4c49-b9a8-abf4d01b51da",
"playlistId": "ccc346ca-e5d1-4403-83ee-4e7d149025e6",
"address": "Online",
"startDate": "2024-06-21T09:30",
"organizer": "TeilzeitKlasse 08/23",
"eventImage": "[/images/header_business.jpg](http://localhost:3000/images/header_business.jpg)",
"createdAt": 1716297341955,
"active": false,
"id": "2abf02bc-b743-4b17-889b-411c3e650f20"
}
]

Playlists:
[
{
"title": "Abschlussfeier",
"djId": "97bd6f95-aa58-4c49-b9a8-abf4d01b51da",
"songs": [],
"createdAt": 1715685457433,
"active": false,
"id": "ccc346ca-e5d1-4403-83ee-4e7d149025e6"
},
{
"title": "Geburtstag",
"djId": "97bd6f95-aa58-4c49-b9a8-abf4d01b51da",
"songs": [],
"createdAt": 1715771992429,
"active": false,
"id": "4fe51a4d-e55a-4399-9ed8-99f12f60ee06"
},
{
"title": "hochzeit",
"djId": "97bd6f95-aa58-4c49-b9a8-abf4d01b51da",
"songs": [],
"createdAt": 1716031813819,
"active": false,
"id": "9ae43aa5-7586-46e9-865d-7189aedc975a"
}
]

users:
[
{
"username": "iris",
"djname": "enyo",
"email": "isch@u",
"phone": "",
"createdAt": 1716478209594,
"id": "b33634b5-ca5f-46fe-8e93-5f8ff92e966e"
}
]

Requests:
[
{
"eventId": "39bb482c-82ab-4650-8439-991534c4bf44",
"artist": "Bob Dylan",
"title": "Like a Rolling Stone",
"who": "{\"id\":1716296357505,\"name\":\"irina\"}",
"message": "Ich grüße das Brautpaar",
"createdAt": 1716296396698,
"open": true,
"likes": 0,
"id": "5de55c83-6ddf-49fb-8be0-c7aa11b725da"
},
{
"eventId": "39bb482c-82ab-4650-8439-991534c4bf44",
"artist": "Michael Jackson",
"title": "Thriller",
"who": "{\"id\":1716410399758,\"name\":\"irina\"}",
"message": "grüße an alle M.J. fans",
"createdAt": 1716410523218,
"open": true,
"likes": 0,
"id": "da12c65e-f5cd-4249-ac5d-368232d8d3ab"
},
{
"eventId": "63ee17ee-ccbc-4018-8b3b-524fd3951ec7",
"artist": "Moop Mama",
"title": "Liebe",
"who": "{\"id\":1716444869101,\"name\":\"irina\"}",
"message": "happy birthday",
"createdAt": 1716445301723,
"open": true,
"likes": 0,
"id": "464cd1d0-57ad-4b04-bdd2-1a19cc3a8d47"
},
{
"eventId": "39bb482c-82ab-4650-8439-991534c4bf44",
"artist": "Guns N' Roses",
"title": "November Rain",
"who": "{\"id\":1716477339515,\"name\":\"irina\"}",
"message": "Grüße an alle. Das ist eine tolle Feier.",
"createdAt": 1716477375484,
"open": true,
"likes": 0,
"id": "7cfef70c-c7fe-4295-a281-1703427a3ae7"
}
]

**Comment by DonLars** [comment]
Hier ist meine db
[db_lars.json](https://github.com/coding-bootcamps-eu/final-project-tz-2023-08-track-stack/files/15422055/db_lars.json)
.json

**Comment by IrisEnyo** [comment]
Und hier meine :)

[db-irina.json](https://github.com/coding-bootcamps-eu/final-project-tz-2023-08-track-stack/files/15433688/db-irina.json)

**Comment by DonLars** [comment]
[db.json](https://github.com/user-attachments/files/15515059/db.json)

Zusammengefasst von Irina und Lars

**Comment by MartinSchneidder** [comment]
Fertig. Ich brauch keine anderen Daten von mir drin.
