### ISSUE TITLE
Design Wireframe Figma

### ISSUE THREAD

**Issue by MartinSchneidder** [coding-bootcamps-eu/final-project-tz-2023-08-track-stack#14]
Design!
Elemente mit Links!

**Comment by DonLars** [comment]
Ist erledigt. 

[TrackStack.pdf](https://github.com/coding-bootcamps-eu/final-project-tz-2023-08-track-stack/files/15040806/TrackStack.pdf)

<img width="482" alt="Bildschirmfoto 2024-04-19 um 15 06 45" src="https://github.com/coding-bootcamps-eu/final-project-tz-2023-08-track-stack/assets/1670167/58359634-b350-447c-a280-ed4eb1594a38">
