### ISSUE TITLE
Überprüfung der Darstellungen unter views

### ISSUE THREAD

**Issue by DonLars** [coding-bootcamps-eu/final-project-tz-2023-08-track-stack#16]
Prüfe bitte ob die von dir angelegten Darstellungen nach unserem Call laut Figma noch valide sind und benenne sie entsprechend eindeutig. Außerdem bitte die Überschrift mit Bezeichnung und groben Infos hinterlegen, was jeweils auf den Views zu erwarten ist. Wenn du Lust hast, kannst du sie auch gerne mit einem Link verknüpfen oder ein Menü erstellen, über das man auf alle Inhalte zugreifen kann.

Have fun ;-)

**Comment by MartinSchneidder** [comment]
Du sprichst über den Code richtig? Oder über die Darstellung in Miro?
Ich geh mal vom Code aus :) obwohl ich Miro auch anpassen werde, falls nötig.

**Comment by DonLars** [comment]
Sorry, ich hatte nicht gelesen, dass du hier geschrieben hast, irgendwie bekomme ich da nix per Mail :-/ Aber alles gut :)
