### ISSUE TITLE
Bug@WishList: Update der Upvotes

### ISSUE THREAD

**Issue by MartinSchneidder** [coding-bootcamps-eu/final-project-tz-2023-08-track-stack#172]
Wenn ich während dem StreamUpdate upvote (zb. ganz schnell upvoten) dann merke ich das der Zähler eins zurückspringt.

Das passiert weil der lokale Wert überschrieben wird, bevor der api Wert geliefert wird.

Anzeige: local:0 api:0
Eingabe: local: eingabe 1 api: gibt gerade 0 zurück
Anzeige: local: anzeige 1 springt auf 0 zurück durch update (KURZE PAUSE) und beim nächsten update wieder auf 1

Wird in dieser PAUSE ein neuer vote gesendet wird auf den alten Wert addiert. => schlecht!

Das werden wir uns vielleicht nochmal später anschauen müssen.

**Comment by MartinSchneidder** [comment]
Ich markier das mal als Question für eine Session mit ferdi :)

**Comment by IrisEnyo** [comment]
Das Problem wurde doch gelöst, oder? 
Kann das issue nicht geschlossen werden?!
