### ISSUE TITLE
guest-wishlist 

### ISSUE THREAD

**Issue by IrisEnyo** [coding-bootcamps-eu/final-project-tz-2023-08-track-stack#173]
- [x] vote up bei gleichem songwunsch
- [ ]  mehrere Messages bei gleichem songwunsch anzeigen
- [x] bei doppelten Wunschtiteln filtern ggf. mit Filter() 

es darf mir gerne auch etwas abgenommen werden 😄

**Comment by DonLars** [comment]
vote up bei gleichem songwunsch (wurde entfernt)
mehrere Messages bei gleichem songwunsch anzeigen (das stellen wir als Feature zurück)
