### ISSUE TITLE
CreateEvent Buttons zusammenbringen

### ISSUE THREAD

**Issue by DonLars** [coding-bootcamps-eu/final-project-tz-2023-08-track-stack#179]
Event hinzufügen und weiter zur Event Übersicht sollte ein Button sein. Also Event hinzufügen müsste einen Alert ausgeben "Event erfolgreich angelegt" und nach dem OK wird man automatisch auf die Übersicht geleitet.

Vielleicht kann man mit:
<input type="submit" value="Event hinzufügen" :disabled="!isFormValid" />

arbeiten, dass das der AbsendeButton ausgegraut ist, solange die Felder nicht ausgefüllt wurden.

**Comment by DonLars** [comment]
<img width="772" alt="image" src="https://github.com/coding-bootcamps-eu/final-project-tz-2023-08-track-stack/assets/1670167/c8d63a5f-ca2c-4f2e-9d6b-35302ae6f4fa">

**Comment by IrisEnyo** [comment]
Der QR Code wird ja erst nach dem hinzufügen des events erstellt. wenn man direkt weitergeleitet wird, hat der user keine möglichkeit den code runterzuladen.

**Comment by DonLars** [comment]
Weiter zu Events.... > Zu den Events
