### ISSUE TITLE
QR Code generieren

### ISSUE THREAD

**Issue by MartinSchneidder** [coding-bootcamps-eu/final-project-tz-2023-08-track-stack#21]
Beschäftige dich mit der Erstellung von QR Codes:

-Es gibt bestimmt ne Api dazu?
-wir ein neuer View benötigt?

-Wie geht das, was macht man damit!!!

**Comment by IrisEnyo** [comment]
Können einen QR Code Generator selbst in unsere App einbauen und evtl. auf der "Create Event" View ausgeben?!

https://www.youtube.com/watch?v=g1j9rR-H1lk

**Comment by DonLars** [comment]
Ja das finde ich eine super Idee. Bei Create Event können wir das ausgeben und bräuchten eine Möglichkeit, dass im edit der Veranstaltung der Code neu generiert wird. Außerdem muss er irgendwie als PDF Datei herunterzuladen sein, damit der DJ diese irgendwo auslegen kann.

**Comment by IrisEnyo** [comment]
Ich würde mal an einer Component für den QR Code rumbasteln, so probeweise, wenn es ok ist?

**Comment by DonLars** [comment]
Ja klar, sehr gerne 👍
