### ISSUE TITLE
CSV import

### ISSUE THREAD

**Issue by MartinSchneidder** [coding-bootcamps-eu/final-project-tz-2023-08-track-stack#22]
Ich denke wir bekommen eine API von Joe gestellt auf der wir Daten speichern können. LocalStorage macht denk ich keinen Sinn. (vll zum Testen)
Auf die API werden dann zb auch die Playlistdaten gespeichert.

Wie geht CSV import! Teste mal!

**Comment by MartinSchneidder** [comment]
Using:
https://www.npmjs.com/package/@usecsv/vuejs3
npm install @usecsv/vuejs3

**Comment by IrisEnyo** [comment]
hast du bereits angefangen es einzubinden? 
sieht auf den ersten blick vielversprechend aus.

**Comment by MartinSchneidder** [comment]
Hab eigentlich noch nix gepushed, ich guck mal

Am Mi., 24. Apr. 2024 um 09:11 Uhr schrieb Irina H. <
***@***.***>:

**Comment by MartinSchneidder** [comment]
Ne, das ist nur das HTML Element von Lars. Das macht gar nix :)

Am Mi., 24. Apr. 2024 um 09:22 Uhr schrieb Martin Schneider <
***@***.***>:
