### ISSUE TITLE
Anonym guest name for message (WishSong > Wishlist)

### ISSUE THREAD

**Issue by DonLars** [coding-bootcamps-eu/final-project-tz-2023-08-track-stack#220]
Es fehlt auch noch die Anonymität wenn jemand seinen Namen nicht veröffentlichen mag.

**Comment by IrisEnyo** [comment]
das ist schon fertig! :D
wenn der gast auf ich möchte anonym bleiben klickt. wird der name beim dj in der message nicht angezeigt.

**Comment by DonLars** [comment]
Ach was okay ... das hatte ich noch gar nicht getestet. Super! 👍
