### ISSUE TITLE
Mustard and hiking buttons

### ISSUE THREAD

**Issue by DonLars** [coding-bootcamps-eu/final-project-tz-2023-08-track-stack#254]
Ich mache mal ein Issue für diese Dinge auf:

- [x] Wandernde Buttons Dropdown bei Mobiler Ansicht

- [x] Wenn noch keine Playlist angelegt ist, darf man eigentlich noch kein Event erstellen dürfen. Wenn der DJ das Event schon ausgefüllt hat, kann er es ohne Playlist weder Zwischenspeichern noch ein Tab parallel aufmachen um dort eine Playlist anzulegen.
- [x] Der Bildausschnitt der Veranstaltung ist generell etwas klein. Wenn es ein Foto mit Menschen drauf ist, kann man es nicht gut erkennen
- [x] Event: Beschreibung muss ein Pflichtfeld sein, sonst kann das Formular nicht abgeschickt werden (ist required)
- [x] Der Hinweis mit dem Download QR Code irritiert. Besser wäre es, wenn der Bereich erst gar nicht sichtbar wäre, erst dann wenn man „Event hinzufügen“ klickt.
- [ ]  Link in Zwischenablage bei Event erstellen

**Comment by IrisEnyo** [comment]
Die 3 Sachen hatte ich eigentlich mit den Sachen die schon emerged wurden hoffentlich erledigt. Musste über main ja zu kontrollieren sein.

Der qr Code funktioniert nicht - > müsste man dann nochmal testen wenn die App endlich online ist. 😒
Bei mir wird die URL (localhost.... /events/dann die ID) angezeigt, wenn ich den qr Code Scanne...
