### ISSUE TITLE
New Logo

### ISSUE THREAD

**Issue by MartinSchneidder** [coding-bootcamps-eu/final-project-tz-2023-08-track-stack#63]
Wir gehen wohl mit HulaLoop!

**Comment by MartinSchneidder** [comment]
So ungefähr?
![Designer30p](https://github.com/coding-bootcamps-eu/final-project-tz-2023-08-track-stack/assets/142412003/a6dc47d9-4e6d-4c18-aa87-ff2f364dc6df)

**Comment by DonLars** [comment]
Hey okay super. Dann würde ich auch mal nen Vorschlag machen. Für Loop hatte ich noch etwas anderes im Kopf, können ja mal sammeln :)

**Comment by DonLars** [comment]
Könnte mit auch die zwei oo im Namen als Unendlichkeitszeichen vorstellen.

**Comment by DonLars** [comment]
![image](https://github.com/coding-bootcamps-eu/final-project-tz-2023-08-track-stack/assets/1670167/3d82e4a9-89b7-4c64-887f-45363c32abf2)
