### ISSUE TITLE
0. DjNamen Dublikate - DJ Registrierung

### ISSUE THREAD

**Issue by MartinSchneidder** [coding-bootcamps-eu/final-project-tz-2023-08-track-stack#75]
Es dürfen keine Dublikate bei der Registrierung auftreten!

**Comment by IrisEnyo** [comment]
auf welchem branch bist du da denn?

**Comment by MartinSchneidder** [comment]
Auf keinem Branch wird auf Dublikate gecheckt. Das brauchen wir aber, sonst ... gibts Probleme mit dem Login (und allen andren Views). Da wir grad nur ein LoginFeld 'DjName' haben, sollte der Name unique sein.

Also kann man sich hierfür einen neuen Branch aufmachen.
Und dann auf Main mergen. Kennste :)
Sonst versteh ich die Frage nicht
